#import uuid
from django.db import models
from django.utils import timezone

class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    completed_at = models.DateTimeField(null=True, blank=True)

    def mark_done(self):
        self.completed_at = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    
class File(models.Model):
    file = models.FileField(upload_to='files/') 

class Project(models.Model):
    project_category = models.CharField(max_length=100, blank=True, null=True)
    project_id = models.CharField(max_length=10, unique=True, null=True)
    project_name = models.CharField(max_length=200, blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    ssite_plans = models.ManyToManyField(File, related_name='ssite_plans', blank=True)
    sketch_2ds = models.ManyToManyField(File, related_name='sketch_2ds', blank=True)
    hand_sketches = models.ManyToManyField(File, related_name='hand_sketches', blank=True)
    sketch_3ds = models.ManyToManyField(File, related_name='sketch_3ds', blank=True)
    ceiling_design_inspiration = models.ManyToManyField(File, related_name='ceiling_design', blank=True)
    wall_design_inspiration = models.ManyToManyField(File, related_name='wall_design',blank=True)
    flooring_inspiration = models.ManyToManyField(File, related_name='flooring_design',blank=True)
    lighting_inspiration = models.ManyToManyField(File, related_name='lighting_design',blank=True)
    exterior_inspiration = models.ManyToManyField(File, related_name='exterior_design',blank=True)
    garden = models.ManyToManyField(File, related_name='garden',blank=True)
    site_plan = models.ManyToManyField(File, related_name='site_plan', blank=True)
    master_plan = models.ManyToManyField(File, related_name='master_plan',blank=True)
    floor_plan_2d = models.ManyToManyField(File, related_name='floor_plans_2d',blank=True)
    elevations = models.ManyToManyField(File, related_name='elevation',blank=True)
    section = models.ManyToManyField(File, related_name='section', blank=True)
    detail_drawing = models.ManyToManyField(File, related_name='detail_drawing', blank=True)
    illustrations_3d = models.ManyToManyField(File, related_name='illustrations_3d', blank=True)
    earthworks_survey = models.ManyToManyField(File, related_name='earthworks_survey', blank=True)
    geo_tech = models.ManyToManyField(File, related_name='geo_tech', blank=True)
    roads = models.ManyToManyField(File, related_name='road', blank=True)
    hydolic_system = models.ManyToManyField(File, related_name='hydolic_system', blank=True)
    structure = models.ManyToManyField(File, related_name='structure', blank=True)
    detailing = models.ManyToManyField(File, related_name='detailing', blank=True)
    water_system = models.ManyToManyField(File, related_name='water_system', blank=True)
    electric = models.ManyToManyField(File, related_name='electric_system', blank=True)
    elv_system = models.ManyToManyField(File, related_name='elv_system', blank=True)
    hvac = models.ManyToManyField(File, related_name='hvac_system', blank=True)
    elevation_system = models.ManyToManyField(File, related_name='elevation_system', blank=True)
    system_safety = models.ManyToManyField(File, related_name='system_safety', blank=True)
    interior_design = models.ManyToManyField(File, related_name='interior_design', blank=True)
    soft_hard_scaping = models.ManyToManyField(File, related_name='soft_hard_scaping',blank=True)
    bill_of_quantities = models.ManyToManyField(File, related_name='bill_of_quantities', blank=True)
    quotation_summary = models.ManyToManyField(File, related_name='quotation_summary',blank=True)
    client_review = models.ManyToManyField(File, related_name='client_review', blank=True)
    final = models.ManyToManyField(File, related_name='final', blank=True)
    contract = models.ManyToManyField(File, related_name='contract', blank=True)
    notary = models.ManyToManyField(File, related_name='notary', blank=True)
    project_payment_plan = models.ManyToManyField(File, related_name='project_payment_plan', blank=True)
    additionals = models.ManyToManyField(File, related_name='additionals', blank=True)
    purchase_order = models.ManyToManyField(File, related_name='purchase_order', blank=True)
    invoice = models.ManyToManyField(File, related_name='invoice', blank=True)
    receipt = models.ManyToManyField(File, related_name='receipt', blank=True)
    purchase_summary = models.ManyToManyField(File, related_name='purchase_summary', blank=True)
    supplier_selection = models.ManyToManyField(File, related_name='supplier_selection', blank=True)
    performance_monitoring = models.ManyToManyField(File, related_name='performance_monitoring', blank=True)
    supplier_classification = models.ManyToManyField(File, related_name='supplier_classification', blank=True)
    partnerships_and_alliances = models.ManyToManyField(File, related_name='partnerships_and_alliances', blank=True)
    other = models.ManyToManyField(File, related_name='other', blank=True)
    contact_information = models.ManyToManyField(File, related_name='contact_information',blank=True)
    interior_finishes = models.ManyToManyField(File, related_name='interior_finishes', blank=True)
    exterior_finishes = models.ManyToManyField(File, related_name='exterior_finishes', blank=True)
    daily_cashflow = models.ManyToManyField(File, related_name='daily_cashflow', blank=True)
    weekly_cashflow = models.ManyToManyField(File, related_name='weekly_cashflow', blank=True)
    monthly_cashflow = models.ManyToManyField(File, related_name='monthly_cashflow', blank=True)
    annual_cashflow = models.ManyToManyField(File, related_name='annual_cashflow', blank=True)
    indirect_costs = models.ManyToManyField(File, related_name='indirect_costs', blank=True)
    cashflow_report = models.ManyToManyField(File, related_name='cashflow_report', blank=True)
    ppurchase_order = models.ManyToManyField(File, related_name='ppurchase_order', blank=True)
    iinvoice = models.ManyToManyField(File, related_name='iinvoice', blank=True)
    rreceipt = models.ManyToManyField(File, related_name='rreceipt', blank=True)
    supplier = models.ManyToManyField(File, related_name='supplier', blank=True)
    account_payable = models.ManyToManyField(File, related_name='account_payable', blank=True)
    scope_of_work = models.CharField(max_length=255, blank=True, null=True)
    invoice_number = models.CharField(max_length=255, blank=True, null=True)
    construction_material= models.CharField(max_length=255, blank=True, null=True)
    equipment = models.CharField(max_length=255, blank=True, null=True)
    tools  = models.CharField(max_length=255, blank=True, null=True)
    other_material = models.CharField(max_length=255, blank=True, null=True)
    raw_material= models.CharField(max_length=255, blank=True, null=True)
    landscaping_material = models.CharField(max_length=255, blank=True, null=True)
    price_comparison = models.CharField(max_length=255, blank=True, null=True)
    
class Brand1(models.Model):
    brand_id= models.CharField(max_length=10, unique=True, null=True)
    affiliate_category = models.CharField(max_length=200, blank=True, null=True)
    sub_category  = models.CharField(max_length=200, blank=True, null=True)
    brand_name= models.FileField(upload_to='brand_name/', blank=True, null=True)
    ceiling_design = models.FileField(upload_to='ceiling_design/', blank=True, null=True)
    wall_design = models.FileField(upload_to='wall_design/', blank=True, null=True)
    flooring = models.FileField(upload_to='flooring/', blank=True, null=True)
    fixture_and_fittings = models.FileField(upload_to='fixture_and_fittings/', blank=True, null=True)
    bathrooom  = models.FileField(upload_to='bathrooom/',blank=True, null=True)
    
class Brand2(models.Model):
    brand_id= models.CharField(max_length=10, unique=True, null=True)
    affiliate_category = models.CharField(max_length=200, blank=True, null=True)
    sub_category  = models.CharField(max_length=200, blank=True, null=True)
    brand_name= models.FileField(upload_to='brand_name/', blank=True, null=True)
    executive_office = models.FileField(upload_to='executive_office/',blank=True, null=True)
    special_designs = models.FileField(upload_to='special_designs/',blank=True, null=True)
    single_office = models.FileField(upload_to='single_office/',blank=True, null=True)
    custom_office = models.FileField(upload_to='custom_office/',blank=True, null=True)
    reception = models.FileField(upload_to='reception/',blank=True, null=True)
    break_room = models.FileField(upload_to='break_room/',blank=True, null=True)
    workstation = models.FileField(upload_to='workstation/',blank=True, null=True)
    small_tables = models.FileField(upload_to='small_tables/',blank=True, null=True)
    decor = models.FileField(upload_to='decor/',blank=True, null=True)
    drapery = models.FileField(upload_to='drapery/',blank=True, null=True)
    art = models.FileField(upload_to='art/',blank=True, null=True)
    carpet = models.FileField(upload_to='carpet/',blank=True, null=True)
    
class Brand3(models.Model):
    brand_id= models.CharField(max_length=10, unique=True, null=True)
    affiliate_category = models.CharField(max_length=200, blank=True, null=True)
    sub_category  = models.CharField(max_length=200, blank=True, null=True)
    brand_name= models.FileField(upload_to='brand_name/', blank=True, null=True)
    living_room = models.FileField(upload_to='living_room/',blank=True, null=True)
    dining_room = models.FileField(upload_to='dining_room/',blank=True, null=True)
    master_bedroom = models.FileField(upload_to='master_bedroom/',blank=True, null=True)
    guest_room = models.FileField(upload_to='guest_room/',blank=True, null=True)
    girls_bedroom = models.FileField(upload_to='girls_bedroom/',blank=True, null=True)
    boys_bedroom = models.FileField(upload_to='boys_bedroom/',blank=True, null=True)
    baby_room = models.FileField(upload_to='baby_room/',blank=True, null=True)
    home_office = models.FileField(upload_to='home_office/',blank=True, null=True)
    balcony = models.FileField(upload_to='balcony/',blank=True, null=True)
    outdoor = models.FileField(upload_to='outdoor/',blank=True, null=True)
    tv_room= models.FileField(upload_to='tv_room/',blank=True, null=True)
    foyer = models.FileField(upload_to='foyer/',blank=True, null=True)
    hallway = models.FileField(upload_to='hallway/',blank=True, null=True)
    lighting2 = models.FileField(upload_to='lighting2/',blank=True, null=True)
    small_tables2= models.FileField(upload_to='small_tables2/',blank=True, null=True)
    decor2= models.FileField(upload_to='decor2/',blank=True, null=True)
    drapery2 = models.FileField(upload_to='drapery2/',blank=True, null=True)
    art2 = models.FileField(upload_to='art2/',blank=True, null=True)
    carpet2 = models.FileField(upload_to='carpet2/',blank=True, null=True)
    bedding = models.FileField(upload_to='bedding/',blank=True, null=True)
    
class Brand4(models.Model):
    brand_id= models.CharField(max_length=10, unique=True, null=True)
    affiliate_category = models.CharField(max_length=200, blank=True, null=True)
    sub_category  = models.CharField(max_length=200, blank=True, null=True)
    brand_name= models.FileField(upload_to='brand_name/', blank=True, null=True)
    stove_and_oven_items = models.FileField(upload_to='stove_and_oven_items/',blank=True, null=True)
    kitchen_electronics= models.FileField(upload_to='kitchen_electronics/',blank=True, null=True)
    cooking_essentials = models.FileField(upload_to='cooking_essentials/',blank=True, null=True)
    serving_essentials= models.FileField(upload_to='serving_essentials/',blank=True, null=True)
    storage = models.FileField(upload_to='storage/',blank=True, null=True)
    accessories = models.FileField(upload_to='accessories/',blank=True, null=True)
    breakfast = models.FileField(upload_to='breakfast/',blank=True, null=True)
    dinner = models.FileField(upload_to='dinner/',blank=True, null=True)
    dessert = models.FileField(upload_to='dessert/',blank=True, null=True)
    cutlery= models.FileField(upload_to='cutlery/',blank=True, null=True)
    beverage= models.FileField(upload_to='beverage/',blank=True, null=True)
    table_accessories = models.FileField(upload_to='table_accessories/',blank=True, null=True)
    table_serving_ware = models.FileField(upload_to='table_serving_ware/',blank=True, null=True)
    tea_coffee = models.FileField(upload_to='tea_coffee/',blank=True, null=True)
    bedsheet= models.FileField(upload_to='bedsheet/',blank=True, null=True)
    mattress= models.FileField(upload_to='mattress/',blank=True, null=True)
    pillows = models.FileField(upload_to='pillows/',blank=True, null=True)
    accessories2 = models.FileField(upload_to='accessories2/',blank=True, null=True)
    drapery3 = models.FileField(upload_to='drapery3/',blank=True, null=True)
    sheer= models.FileField(upload_to='sheer/',blank=True, null=True)
    accessories3= models.FileField(upload_to='accessories3/',blank=True, null=True)
    carpet4= models.FileField(upload_to='carpet4/',blank=True, null=True)
    decor4= models.FileField(upload_to='decor4/',blank=True, null=True)

class EC_Admins(models.Model):
    ecadmin_id = models.CharField(max_length=50, unique=True)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    middlename = models.CharField(max_length=100)
    gender = models.CharField(max_length=6)
    dateofbirth = models.DateField()
    address = models.CharField(max_length=1024)
    pincode = models.CharField(max_length=6)
    mobile_no = models.BigIntegerField(unique=True)
    email = models.EmailField(max_length=254, unique=True)
    ecadmin_image = models.ImageField(upload_to='ECAdminImage/')


    def __str__(self):
        return self.ecadmin_id